version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install pylint
      - pip install bandit

  pre_build:
    commands:
      - pylint manage.py | tee pylint_report.txt
      - bandit -r manage.py | tee bandit_report.txt

  post_build:
    commands:
      - echo "Pylint report:"
      - cat pylint_report.txt
      - echo "Bandit report:"
      - cat bandit_report.txt
artifacts:
    files:
        - '**/*'

